### ISSUE TITLE
Roadmap 1.0

### ISSUE THREAD

**Issue by jupiter** [tcdl/msb#39]
We would like to release a 1.0 version of MSB, for both NodeJS and other platforms. Being at 1.0 will mean that we guarantee backward-compatibility as per [Semver](http://semver.org). There has been some discussion on various topics that I would like to bring together into a roadmap for 1.0.

These are the topics I would like to expand upon:
- [x] Node 4 Compatibility #41 
- [ ] Schema/API Freeze
- [ ] Cross-platform integration testing
- [ ] Load Testing (long-running, unthrottled)
- [ ] Release Management
- [x] Contribution Guidelines #40
- [x] Capability of multiple, different brokers in the same process #52

**Comment by jupiter** [comment]
@HCanber has suggested in #61 we move to Node 4. I think this makes sense and should be included in 1.0.
